<#
  switch-dsh-web-to-user.ps1 — 把 dsh-web 从「nssm 服务（LocalSystem）」切到「以 lk 身份运行的交互式计划任务」

  为什么这么做：沙箱后端 dsh-sandbox-windows-acl 的受限令牌**必须**带 logon SID，而 LocalSystem
  的令牌天然没有 → 以服务方式运行 DSH 时该后端起不来，workspace-write 下 shell 会 fail-closed。
  真实用户身份的登录会话自带 logon SID，所以只要让它以 lk 运行即可。交互式计划任务（/it）在
  用户已登录时无需密码，这是本机唯一不需要账户密码的可行路径。

  为什么不是「nssm 服务改用 lk 账户」：那需要账户密码。上面那条命令实测报错
  「The user name or password is incorrect」（系统日志 id 7038）。

  用法（**以管理员身份**打开 PowerShell）：
      powershell -ExecutionPolicy Bypass -File D:\FF\project-nav\docs\switch-dsh-web-to-user.ps1
  回滚：
      powershell -ExecutionPolicy Bypass -File D:\FF\project-nav\docs\switch-dsh-web-to-user.ps1 -Rollback

  安全性：不删除服务，只 `stop` + 置 `Start=disabled`（一键可恢复）；新实例起不来会自动回滚。
#>

[CmdletBinding()]
param(
  [string]$Service  = 'dsh-web',
  [string]$TaskName = 'dsh-web-user',
  [string]$Account  = "$env:COMPUTERNAME\lk",
  [int]   $Port     = 3080,
  [switch]$Rollback
)

$ErrorActionPreference = 'Stop'
$stamp   = Get-Date -Format 'yyyyMMdd-HHmmss'
$Backup  = Join-Path $env:USERPROFILE ".dsh\backups\switch-to-user-$stamp"
$LogDir  = Join-Path $env:USERPROFILE '.dsh\logs'
$Wrapper = Join-Path $env:USERPROFILE '.dsh\dsh-web-user.cmd'
$OutLog  = Join-Path $LogDir 'dsh-web-user-out.log'
$RunLog  = Join-Path $Backup 'switch.log'

function Step($n, $m) { Write-Host "`n[$n] $m" -ForegroundColor Cyan; Add-Content $RunLog "[$n] $m" }
function Ok($m)   { Write-Host "    PASS  $m" -ForegroundColor Green;  Add-Content $RunLog "  PASS $m" }
function Warn($m) { Write-Host "    WARN  $m" -ForegroundColor Yellow; Add-Content $RunLog "  WARN $m" }
function Die($m)  { Write-Host "`n    FAIL  $m" -ForegroundColor Red; Add-Content $RunLog "  FAIL $m"; exit 1 }

function Listening([int]$p) { [bool](Get-NetTCPConnection -State Listen -LocalPort $p -ErrorAction SilentlyContinue) }
function Wait-Port([int]$p, [int]$sec = 120) {
  $end = (Get-Date).AddSeconds($sec)
  while ((Get-Date) -lt $end) { if (Listening $p) { return $true }; Start-Sleep -Milliseconds 800 }
  return $false
}
# owner of the process listening on $p (the point of the whole exercise: it must be lk)
function PortOwner([int]$p) {
  $c = Get-NetTCPConnection -State Listen -LocalPort $p -ErrorAction SilentlyContinue | Select-Object -First 1
  if (-not $c) { return $null }
  $o = (Get-CimInstance Win32_Process -Filter "ProcessId=$($c.OwningProcess)" -ErrorAction SilentlyContinue).GetOwner()
  if (-not $o) { return $null }
  return "$($o.Domain)\$($o.User)"
}

function Restore-Service([string]$why) {
  Warn "回滚中（$why）"
  & schtasks /end /tn $TaskName *> $null
  & schtasks /delete /tn $TaskName /f *> $null
  & sc.exe config $Service start= auto | Out-Null
  & sc.exe start $Service | Out-Null
  if (Wait-Port $Port 120) {
    Ok "nssm 服务已恢复并重新监听 $Port（当前状态 = 变更前）"
  } else {
    Warn "服务已恢复但 $Port 未就绪，请查 $((Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Services\$Service" -Name AppStderr -ErrorAction SilentlyContinue).AppStderr)"
  }
  Write-Host "`n日志：$RunLog" -ForegroundColor Yellow
  exit 1
}

New-Item -ItemType Directory -Force -Path $Backup, $LogDir | Out-Null

# ---------------------------------------------------------------- 0. 前置
Step 0 '前置检查'
$pr = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $pr.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { Die '需要管理员权限' }
Ok '以管理员身份运行'
$sess = & quser 2>$null | Select-String ([regex]::Escape(($Account -split '\\')[-1]))
if (-not $sess) { Die "账户 $Account 当前没有交互登录会话 —— 交互式计划任务无法启动（请先登录该账户）" }
Ok "$Account 已在交互登录会话中（/it 任务不需要密码）"

# ---------------------------------------------------------------- 1. 备份
Step 1 '备份（可回滚的前提）'
& reg.exe export "HKLM\SYSTEM\CurrentControlSet\Services\$Service" (Join-Path $Backup "$Service-service.reg") /y | Out-Null
Ok "服务注册表 -> $(Join-Path $Backup "$Service-service.reg")"
$params = Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Services\$Service\Parameters"
$app  = $params.Application
$args = $params.AppParameters
$dir  = $params.AppDirectory
$envx = @($params.AppEnvironmentExtra)
$app | Set-Content (Join-Path $Backup 'launch.txt') -Encoding UTF8
"AppParameters: $args" | Add-Content (Join-Path $Backup 'launch.txt') -Encoding UTF8
"AppDirectory : $dir"  | Add-Content (Join-Path $Backup 'launch.txt') -Encoding UTF8
if (-not $app -or -not $args) { Die '读不到 nssm 的 Application/AppParameters，无法复刻启动命令' }
Ok "启动命令已留档（$app）"

if ($Rollback) {
  Step 2 '回滚模式'
  Restore-Service '用户请求回滚'
  Ok '完成'
  exit 0
}

# ---------------------------------------------------------------- 2. 包装脚本（ASCII only：.cmd 的编码比 .ps1 更脆）
Step 2 "生成启动包装 -> $Wrapper"
$envLines = @()
foreach ($e in $envx) { if ($e -and $e.Trim()) { $envLines += "set $($e.Trim())" } }
$cmd = @(
  '@echo off',
  'rem generated by switch-dsh-web-to-user.ps1 -- ASCII only on purpose',
  'rem Why a scheduled task as the logged-on user: the Windows ACL sandbox backend needs a',
  'rem logon SID in the process token; LocalSystem has none, a real user logon does.',
  'set DSH_STARTED_BY=task:' + $TaskName
) + $envLines + @(
  "cd /d `"$dir`"",
  "`"$app`" $args >> `"$OutLog`" 2>&1"
)
Set-Content -Path $Wrapper -Value $cmd -Encoding ASCII
Ok "包装脚本已写入（$($cmd.Count) 行）"

# ---------------------------------------------------------------- 3. 计划任务
Step 3 "创建交互式计划任务 -> $TaskName"
& schtasks /create /tn $TaskName /tr "`"$Wrapper`"" /sc onlogon /ru $Account /rl highest /it /f *> $null
if ($LASTEXITCODE -ne 0) { Die "schtasks /create 失败（exit $LASTEXITCODE）" }
$q = & schtasks /query /tn $TaskName /fo list 2>$null
if (-not $q) { Die '任务创建后查询不到' }
Ok "任务已创建（onlogon · 最高权限 · 仅用户登录时运行）"

# ---------------------------------------------------------------- 4. 停用 nssm 服务
Step 4 '停用 nssm 服务（只停不禁，可一键恢复）'
& sc.exe stop $Service | Out-Null
$end = (Get-Date).AddSeconds(90)
while ((Get-Date) -lt $end) { if ((Get-Service $Service).Status -eq 'Stopped') { break }; Start-Sleep -Milliseconds 800 }
if ((Get-Service $Service).Status -ne 'Stopped') { Restore-Service '服务未能停止' }
Ok '服务已停止'
& sc.exe config $Service start= disabled | Out-Null
Ok '服务已置为 disabled（重启后不会自启；随时可 config start= auto 恢复）'

# ---------------------------------------------------------------- 5. 启动新实例
Step 5 "启动任务并等待 $Port"
& schtasks /run /tn $TaskName | Out-Null
if (-not (Wait-Port $Port 150)) { Restore-Service '新实例未能在 150 秒内监听端口' }
Ok "端口 $Port 已监听"
$owner = PortOwner $Port
if ($owner -and ($owner -notmatch [regex]::Escape(($Account -split '\\')[-1]))) {
  Restore-Service "监听 $Port 的进程所有者是 $owner，不是 $Account"
}
Ok "监听进程所有者 = $owner（含 logon SID，沙箱后端可用）"

# ---------------------------------------------------------------- 6. 新 token
Step 6 '取新访问地址'
if (Test-Path $OutLog) {
  try {
    $fs = [System.IO.File]::Open($OutLog, 'Open', 'Read', 'ReadWrite')
    $sr = New-Object System.IO.StreamReader($fs)
    $tail = $sr.ReadToEnd(); $sr.Close(); $fs.Close()
    $m = [regex]::Matches($tail, 'http://127\.0\.0\.1:\d+/\?token=\S+')
    if ($m.Count -gt 0) { Write-Host "    $($m[$m.Count - 1].Value)" -ForegroundColor Green }
    else { Warn "日志里暂无 token URL，稍后查看 $OutLog" }
  } catch { Warn "读日志失败：$($_.Exception.Message)" }
} else { Warn "尚无输出日志：$OutLog" }

$summary = @"

==================== 接下来验证 ====================
1) 进程身份（应显示 $Account）
     (Get-CimInstance Win32_Process -Filter "Name='node.exe'").GetOwner() | Select-Object User

2) 沙箱后端真的能用了（在任一会话里）
     /permission workspace-write
     Get-Date          # 修复前：no sandbox backend is usable；修复后：正常执行
     /permission danger-full-access

3) 服务已停用但未删除
     恢复：sc.exe config $Service start= auto ; sc.exe start $Service
     彻底删除（确认稳定后再做）：nssm remove $Service confirm

日志：$RunLog
包装：$Wrapper
备份：$Backup
====================================================
"@
Write-Host $summary -ForegroundColor Cyan
